Disable legacy and additional build jobs in CI
Comment out legacy and other build jobs in CI configuration.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,127 +5,127 @@ on:
   - workflow_dispatch
 
 jobs:
-  build-linux-legacy:
-    name: Linux (legacy)
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v4
+#   build-linux-legacy:
+#     name: Linux (legacy)
+#     runs-on: ubuntu-latest
+#     steps:
+#     - name: Checkout
+#       uses: actions/checkout@v4
 
-    - name: Build
-      run: docker build -f .github/workflows/Dockerfile.legacy .
+#     - name: Build
+#       run: docker build -f .github/workflows/Dockerfile.legacy .
 
-################################################################################
+# ################################################################################
 
-  build-linux-qt6:
-    name: Linux (Qt6)
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v4
+#   build-linux-qt6:
+#     name: Linux (Qt6)
+#     runs-on: ubuntu-latest
+#     steps:
+#     - name: Checkout
+#       uses: actions/checkout@v4
 
-    - name: Build
-      run: docker build -f .github/workflows/Dockerfile.arch-qt6 .
+#     - name: Build
+#       run: docker build -f .github/workflows/Dockerfile.arch-qt6 .
 
-################################################################################
+# ################################################################################
 
-  build-sanitizer:
-    name: Sanitizer (Linux)
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v4
+#   build-sanitizer:
+#     name: Sanitizer (Linux)
+#     runs-on: ubuntu-latest
+#     steps:
+#     - name: Checkout
+#       uses: actions/checkout@v4
 
-    - name: Build
-      run: docker build -f .github/workflows/Dockerfile.sanitizer .
+#     - name: Build
+#       run: docker build -f .github/workflows/Dockerfile.sanitizer .
 
-################################################################################
+# ################################################################################
 
-  coverage-linux:
-    name: Coverage (Linux)
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v4
+#   coverage-linux:
+#     name: Coverage (Linux)
+#     runs-on: ubuntu-latest
+#     steps:
+#     - name: Checkout
+#       uses: actions/checkout@v4
 
-    - name: Install dependencies
-      run: sudo apt update && sudo apt install --assume-yes --no-install-recommends libhunspell-dev liblua5.4-dev libpoppler-qt6-dev libpoppler-private-dev make poppler-data qt6-5compat-dev qt6-base-dev qt6-declarative-dev qt6-tools-dev qt6-tools-dev-tools zlib1g-dev xvfb fonts-urw-base35 poppler-data lcov
+#     - name: Install dependencies
+#       run: sudo apt update && sudo apt install --assume-yes --no-install-recommends libhunspell-dev liblua5.4-dev libpoppler-qt6-dev libpoppler-private-dev make poppler-data qt6-5compat-dev qt6-base-dev qt6-declarative-dev qt6-tools-dev qt6-tools-dev-tools zlib1g-dev xvfb fonts-urw-base35 poppler-data lcov
 
-    - name: Configure
-      run: cmake -B build -DCMAKE_BUILD_TYPE="Debug" -DWITH_COVERAGE=On .
+#     - name: Configure
+#       run: cmake -B build -DCMAKE_BUILD_TYPE="Debug" -DWITH_COVERAGE=On .
 
-    - name: Build
-      run: cmake --build build
+#     - name: Build
+#       run: cmake --build build
 
-    - name: Test
-      working-directory: build
-      run: |
-        echo "::group::Initialization"
-        lcov --zerocounters --directory .
-        lcov --capture --initial --directory . --output-file "coverage.base"
-        lcov --remove "coverage.base" '/usr/*' --output-file "coverage.base"
-        lcov --remove "coverage.base" "$(pwd)"'/*_autogen/*' --output-file "coverage.base"
-        echo "::endgroup::"
-        echo "::group::Run tests"
-        xvfb-run ctest -V
-        echo "::endgroup::"
-        echo "::group::Collect data"
-        lcov --capture --directory . --output-file "coverage.info"
-        lcov --remove "coverage.info" '/usr/*' --output-file "coverage.info"
-        lcov --remove "coverage.info" "$(pwd)"'/*_autogen/*' --output-file "coverage.info"
-        lcov --add-tracefile "coverage.base" --add-tracefile "coverage.info" --output-file "coverage.info"
-        echo "::endgroup::"
-        echo "::group::Info"
-        lcov --list coverage.info #debug info
-        echo "::endgroup::"
-    - name: Upload to Codecov
-      uses: codecov/codecov-action@v5
-      with:
-        fail_ci_if_error: true
-        token: ${{ secrets.CODECOV_TOKEN }}
-        verbose: true
+#     - name: Test
+#       working-directory: build
+#       run: |
+#         echo "::group::Initialization"
+#         lcov --zerocounters --directory .
+#         lcov --capture --initial --directory . --output-file "coverage.base"
+#         lcov --remove "coverage.base" '/usr/*' --output-file "coverage.base"
+#         lcov --remove "coverage.base" "$(pwd)"'/*_autogen/*' --output-file "coverage.base"
+#         echo "::endgroup::"
+#         echo "::group::Run tests"
+#         xvfb-run ctest -V
+#         echo "::endgroup::"
+#         echo "::group::Collect data"
+#         lcov --capture --directory . --output-file "coverage.info"
+#         lcov --remove "coverage.info" '/usr/*' --output-file "coverage.info"
+#         lcov --remove "coverage.info" "$(pwd)"'/*_autogen/*' --output-file "coverage.info"
+#         lcov --add-tracefile "coverage.base" --add-tracefile "coverage.info" --output-file "coverage.info"
+#         echo "::endgroup::"
+#         echo "::group::Info"
+#         lcov --list coverage.info #debug info
+#         echo "::endgroup::"
+#     - name: Upload to Codecov
+#       uses: codecov/codecov-action@v5
+#       with:
+#         fail_ci_if_error: true
+#         token: ${{ secrets.CODECOV_TOKEN }}
+#         verbose: true
 
-################################################################################
+# ################################################################################
 
-  build-win-msys:
-    name: Windows (MSYS)
-    runs-on: windows-latest
-    if: false
-    defaults:
-      run:
-        shell: msys2 {0}
+  # build-win-msys:
+  #   name: Windows (MSYS)
+  #   runs-on: windows-latest
+  #   if: false
+  #   defaults:
+  #     run:
+  #       shell: msys2 {0}
 
-    steps:
-    - name: Configure Git
-      run: git config --global core.autocrlf input
-      shell: bash
+  #   steps:
+  #   - name: Configure Git
+  #     run: git config --global core.autocrlf input
+  #     shell: bash
 
-    - name: Setup MSYS
-      uses: msys2/setup-msys2@v2
-      with:
-        update: true
-        install: mingw-w64-x86_64-cmake git make mingw-w64-x86_64-gcc mingw-w64-x86_64-hunspell mingw-w64-x86_64-lua mingw-w64-x86_64-poppler mingw-w64-x86_64-qt5
+  #   - name: Setup MSYS
+  #     uses: msys2/setup-msys2@v2
+  #     with:
+  #       update: true
+  #       install: mingw-w64-x86_64-cmake git make mingw-w64-x86_64-gcc mingw-w64-x86_64-hunspell mingw-w64-x86_64-lua mingw-w64-x86_64-poppler mingw-w64-x86_64-qt5
 
-    - name: Checkout
-      uses: actions/checkout@v4
+  #   - name: Checkout
+  #     uses: actions/checkout@v4
 
-    - name: Configure
-      run: cmake -G 'MSYS Makefiles' -B build -DTW_BUILD_ID='github' -DTEXWORKS_ADDITIONAL_LIBS='shlwapi' -DQT_DEFAULT_MAJOR_VERSION=5
+  #   - name: Configure
+  #     run: cmake -G 'MSYS Makefiles' -B build -DTW_BUILD_ID='github' -DTEXWORKS_ADDITIONAL_LIBS='shlwapi' -DQT_DEFAULT_MAJOR_VERSION=5
 
-    - name: Build
-      run: cmake --build build -j
+  #   - name: Build
+  #     run: cmake --build build -j
 
-    - name: Test
-      run: ctest -V
-      working-directory: build
-      env:
-        QT_FORCE_STDERR_LOGGING: 1
+  #   - name: Test
+  #     run: ctest -V
+  #     working-directory: build
+  #     env:
+  #       QT_FORCE_STDERR_LOGGING: 1
 
 ################################################################################
 
   build-win-msvc:
     name: Windows (MSVC)
-    runs-on: windows-latest
+    runs-on: windows-11-arm
 
     steps:
     - name: Checkout
@@ -137,18 +137,13 @@ jobs:
         version: 6.8.*
         modules: qt5compat
 
-      # Strawberry perl comes with all sorts of libraries (without headers) that
-      # can wreak havoc when building some of the dependencies
-    - name: Remove Strawberry Perl
-      run: rm -r -fo C:/Strawberry
-
     - name: Install dependencies
       run: |
-        cmake -B "${{ runner.workspace }}/tw-deps-build" -S "${{ github.workspace }}/.github/actions/msvc-dependencies" -DCMAKE_INSTALL_PREFIX="${{ runner.workspace }}/tw-deps"
+        cmake -A ARM64 -B "${{ runner.workspace }}/tw-deps-build" -S "${{ github.workspace }}/.github/actions/msvc-dependencies" -DCMAKE_INSTALL_PREFIX="${{ runner.workspace }}/tw-deps"
         cmake --build "${{ runner.workspace }}/tw-deps-build" --config Release
 
     - name: Configure
-      run: cmake -B build -DTW_BUILD_ID='github' -DCMAKE_PREFIX_PATH="${{ runner.workspace }}/tw-deps" -Dgp_tool='none' -DQT_DEFAULT_MAJOR_VERSION=6
+      run: cmake -A ARM64 -B build -DTW_BUILD_ID='github' -DCMAKE_PREFIX_PATH="${{ runner.workspace }}/tw-deps" -Dgp_tool='none' -DQT_DEFAULT_MAJOR_VERSION=6
 
     - name: Build
       run: cmake --build build --config Release
@@ -165,72 +160,72 @@ jobs:
       env:
         QT_FORCE_STDERR_LOGGING: 1
 
-################################################################################
+# ################################################################################
 
-  macosx-homebrew:
-    name: Mac OS X (Homebrew)
-    runs-on: macos-latest
+#   macosx-homebrew:
+#     name: Mac OS X (Homebrew)
+#     runs-on: macos-latest
 
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v4
+#     steps:
+#     - name: Checkout
+#       uses: actions/checkout@v4
 
-    - name: Install Dependencies
-      run: |
-        # /usr/local/bin/2to3 and some other programs, as well as versioned
-        # variants (e.g. 2to3-3.11) are symlinked to the native python
-        # installation but prevent the homebrew install from succeeding
-        # So we remove them
-        cd /usr/local/bin && rm -f 2to3* idle* pydoc* python*
-        brew update > /tmp/brew_update.log || { echo "::error::Updating homebrew failed"; cat /tmp/brew_update.log; exit 1; }
-        brew install hunspell poppler-qt5 lua qt@5
-        # As poppler-qt5 conflicts with poppler, we need to force-link it
-        brew link --force poppler-qt5
+#     - name: Install Dependencies
+#       run: |
+#         # /usr/local/bin/2to3 and some other programs, as well as versioned
+#         # variants (e.g. 2to3-3.11) are symlinked to the native python
+#         # installation but prevent the homebrew install from succeeding
+#         # So we remove them
+#         cd /usr/local/bin && rm -f 2to3* idle* pydoc* python*
+#         brew update > /tmp/brew_update.log || { echo "::error::Updating homebrew failed"; cat /tmp/brew_update.log; exit 1; }
+#         brew install hunspell poppler-qt5 lua qt@5
+#         # As poppler-qt5 conflicts with poppler, we need to force-link it
+#         brew link --force poppler-qt5
 
-    - name: Configure
-      run: cmake -B build -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE} -DCMAKE_PREFIX_PATH="`brew --prefix qt@5`" -DQT_DEFAULT_MAJOR_VERSION=5
+#     - name: Configure
+#       run: cmake -B build -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE} -DCMAKE_PREFIX_PATH="`brew --prefix qt@5`" -DQT_DEFAULT_MAJOR_VERSION=5
 
-    - name: Build
-      run: make -j
-      working-directory: build
+#     - name: Build
+#       run: make -j
+#       working-directory: build
 
-    - name: Test
-      run: ctest -V
-      working-directory: build
+#     - name: Test
+#       run: ctest -V
+#       working-directory: build
 
-################################################################################
+# ################################################################################
 
-  build-macosx-macports:
-    name: Mac OS X (MacPorts)
-    runs-on: macos-latest
-    if: false
-    strategy:
-      matrix:
-        include:
-        - macports-version: 2.6.2
-          macports-platform: 10.15-Catalina
+#   build-macosx-macports:
+#     name: Mac OS X (MacPorts)
+#     runs-on: macos-latest
+#     if: false
+#     strategy:
+#       matrix:
+#         include:
+#         - macports-version: 2.6.2
+#           macports-platform: 10.15-Catalina
 
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v4
+#     steps:
+#     - name: Checkout
+#       uses: actions/checkout@v4
 
-    - name: Install MacPorts
-      run: |
-        wget https://github.com/macports/macports-base/releases/download/v${{ matrix.macports-version }}/MacPorts-${{ matrix.macports-version }}-${{ matrix.macports-platform }}.pkg
-        sudo /usr/sbin/installer -pkg MacPorts-${{ matrix.macports-version }}-${{ matrix.macports-platform }}.pkg -target /
-        echo "::add-path::/opt/local/bin:/opt/local/sbin"
+#     - name: Install MacPorts
+#       run: |
+#         wget https://github.com/macports/macports-base/releases/download/v${{ matrix.macports-version }}/MacPorts-${{ matrix.macports-version }}-${{ matrix.macports-platform }}.pkg
+#         sudo /usr/sbin/installer -pkg MacPorts-${{ matrix.macports-version }}-${{ matrix.macports-platform }}.pkg -target /
+#         echo "::add-path::/opt/local/bin:/opt/local/sbin"
 
-    - name: Install Dependencies
-      run: sudo port selfupdate && sudo port install hunspell lua poppler-qt5 qt5-qtbase qt5-qtdeclarative qt5-qtscript qt5-qttools
+#     - name: Install Dependencies
+#       run: sudo port selfupdate && sudo port install hunspell lua poppler-qt5 qt5-qtbase qt5-qtdeclarative qt5-qtscript qt5-qttools
 
-    - name: Configure
-      run: cmake -B build -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE} -DQT_DEFAULT_MAJOR_VERSION=5
+#     - name: Configure
+#       run: cmake -B build -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE} -DQT_DEFAULT_MAJOR_VERSION=5
 
-    - name: Build
-      run: make -j
-      working-directory: build
+#     - name: Build
+#       run: make -j
+#       working-directory: build
 
-    - name: Test
-      run: ctest -V
-      working-directory: build
+#     - name: Test
+#       run: ctest -V
+#       working-directory: build
 
